<?php defined('ABSPATH') || exit; ?>
<section class="section section-soft" data-module="applications">
<div class="shell">
<p class="eyebrow"><?php echo esc_html(tio2_field('applications.eyebrow.1')); ?></p><h2 class="section-title"><?php echo esc_html(tio2_field('applications.heading.1')); ?></h2><p class="section-intro"><?php echo esc_html(tio2_field('applications.paragraph.1')); ?></p>
<div class="cards application-grid" style="margin-top:34px">
<article class="card application-card"><span class="symbol"><?php echo esc_html(tio2_field('applications.span.1')); ?></span><h3><?php echo esc_html(tio2_field('applications.card-title.1')); ?></h3><p><?php echo esc_html(tio2_field('applications.paragraph.2')); ?></p><a class="text-link" href="<?php echo esc_url(tio2_field('applications.link.1')); ?>"><?php echo esc_html(tio2_field('applications.link-label.1')); ?></a></article>
<article class="card application-card"><span class="symbol"><?php echo esc_html(tio2_field('applications.span.2')); ?></span><h3><?php echo esc_html(tio2_field('applications.card-title.2')); ?></h3><p><?php echo esc_html(tio2_field('applications.paragraph.3')); ?></p><a class="text-link" href="<?php echo esc_url(tio2_field('applications.link.2')); ?>"><?php echo esc_html(tio2_field('applications.link-label.2')); ?></a></article>
<article class="card application-card"><span class="symbol"><?php echo esc_html(tio2_field('applications.span.3')); ?></span><h3><?php echo esc_html(tio2_field('applications.card-title.3')); ?></h3><p><?php echo esc_html(tio2_field('applications.paragraph.4')); ?></p><a class="text-link" href="<?php echo esc_url(tio2_field('applications.link.3')); ?>"><?php echo esc_html(tio2_field('applications.link-label.3')); ?></a></article>
<article class="card application-card"><span class="symbol"><?php echo esc_html(tio2_field('applications.span.4')); ?></span><h3><?php echo esc_html(tio2_field('applications.card-title.4')); ?></h3><p><?php echo esc_html(tio2_field('applications.paragraph.5')); ?></p><a class="text-link" href="<?php echo esc_url(tio2_field('applications.link.4')); ?>"><?php echo esc_html(tio2_field('applications.link-label.4')); ?></a></article>
<article class="card application-card"><span class="symbol"><?php echo esc_html(tio2_field('applications.span.5')); ?></span><h3><?php echo esc_html(tio2_field('applications.card-title.5')); ?></h3><p><?php echo esc_html(tio2_field('applications.paragraph.6')); ?></p><a class="text-link" href="<?php echo esc_url(tio2_field('applications.link.5')); ?>"><?php echo esc_html(tio2_field('applications.link-label.5')); ?></a></article>
</div>
</div>
</section>
