<?php defined('ABSPATH') || exit; ?>
<section class="section" data-module="products">
<div class="shell">
<div class="product-head"><div><p class="eyebrow"><?php echo esc_html(tio2_field('products.eyebrow.1')); ?></p><h2 class="section-title"><?php echo esc_html(tio2_field('products.heading.1')); ?></h2><p class="section-intro"><?php echo esc_html(tio2_field('products.paragraph.1')); ?></p></div><div class="grade-count"><strong><?php echo esc_html(tio2_field('products.strong.1')); ?></strong><span><?php echo esc_html(tio2_field('products.span.1')); ?></span></div></div>
<div class="product-grid">
<details class="product-group" open=""><summary><?php echo esc_html(tio2_field('products.group-title.1')); ?><span aria-hidden="true">+</span></summary><div class="product-body"><p><?php echo esc_html(tio2_field('products.paragraph.2')); ?></p><div class="grades"><span><?php echo esc_html(tio2_field('products.grade.1')); ?></span><span><?php echo esc_html(tio2_field('products.grade.2')); ?></span><span><?php echo esc_html(tio2_field('products.grade.3')); ?></span><span><?php echo esc_html(tio2_field('products.grade.4')); ?></span><span><?php echo esc_html(tio2_field('products.grade.5')); ?></span><span><?php echo esc_html(tio2_field('products.grade.6')); ?></span></div></div></details>
<details class="product-group" open=""><summary><?php echo esc_html(tio2_field('products.group-title.2')); ?><span aria-hidden="true">+</span></summary><div class="product-body"><p><?php echo esc_html(tio2_field('products.paragraph.3')); ?></p><div class="grades"><span><?php echo esc_html(tio2_field('products.grade.7')); ?></span><span><?php echo esc_html(tio2_field('products.grade.8')); ?></span><span><?php echo esc_html(tio2_field('products.grade.9')); ?></span><span><?php echo esc_html(tio2_field('products.grade.10')); ?></span><span><?php echo esc_html(tio2_field('products.grade.11')); ?></span></div></div></details>
<details class="product-group" open=""><summary><?php echo esc_html(tio2_field('products.group-title.3')); ?><span aria-hidden="true">+</span></summary><div class="product-body"><p><?php echo esc_html(tio2_field('products.paragraph.4')); ?></p><div class="grades"><span><?php echo esc_html(tio2_field('products.grade.12')); ?></span><span><?php echo esc_html(tio2_field('products.grade.13')); ?></span></div></div></details>
<details class="product-group" open=""><summary><?php echo esc_html(tio2_field('products.group-title.4')); ?><span aria-hidden="true">+</span></summary><div class="product-body"><p><?php echo esc_html(tio2_field('products.paragraph.5')); ?></p><div class="grades"><span><?php echo esc_html(tio2_field('products.grade.14')); ?></span></div></div></details>
</div>
<div class="product-actions"><div class="process-links"><a class="text-link" href="<?php echo esc_url(tio2_field('products.link.1')); ?>"><?php echo esc_html(tio2_field('products.link-label.1')); ?></a><a class="text-link" href="<?php echo esc_url(tio2_field('products.link.2')); ?>"><?php echo esc_html(tio2_field('products.link-label.2')); ?></a></div><a class="primary" href="<?php echo esc_url(tio2_field('products.link.3')); ?>"><?php echo esc_html(tio2_field('products.link-label.3')); ?></a></div>
</div>
</section>
